### ISSUE TITLE
Generate bindings for getopt.h

### ISSUE THREAD

**Issue by frgomes** [frgomes/scala-bindgen#11]
- [ ] #12  - Proposal for output format;
- [ ] #13  - Proposal for processing multiple files and ``#include`` directives;
- [ ] #14   - Proposal for boilerplate aiming passing values by reference;
- [ ] #16 - Proposal for binding enumerations
- [ ] #17 - Proposal for keeping C compile-time information into Scala generated bindings
- [ ] some more here...
